language: python
cache: pip

python:
    - "3.8"

sudo: false

matrix:
    fast_finish: true
    include:
        - python: 3.8
          env: TOXENV=flake8

install:
    - pip install coverage tox tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
email: false