language: python
cache: pip

python:
    - "3.8"

sudo: false

install:
    - pip install -U pip
    - pip install -U pytest
    - pip install coverage tox tox-travis
    - pip install codecov
script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
email: false