language: python
cache: pip

python:
    - "3.8"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y
    - sudo apt-get install -y python-gmsh
    - sudo apt-get install wine-stable
    - wget https://www.femm.info/wiki/Files/files.xml?action=download&file=femm42bin_win32_21Apr2019.exe
    - wine femm42bin_win32_21Apr2019.exe

install:
    - pip install -U pip
    - pip install -U pytest
    - pip install coverage tox-travis
    - pip install pygmsh
script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
email: false
