language: python
cache: pip

python:
    - "3.8"

sudo: false

install:
    - pip install coverage tox-travis

script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
email: false