language: python
cache: pip

python:
    - "3.8"

sudo: true

before_install:
    - sudo apt-get install python3-gmsh

install:
    - pip install -U pip
    - pip install -U pytest
    - pip install coverage tox-travis
    - pip install pygmsh
script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
email: false