language: python
cache: pip

python:
    - "3.8"

before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
    - sudo apt-get update -y
    - sudo apt-get install -y python-gmsh
    - wget -nc https://dl.winehq.org/wine-builds/winehq.key
    - sudo gpg -o /etc/apt/trusted.gpg.d/winehq.key.gpg --dearmor winehq.key
    - sudo add-apt-repository 'deb https://dl.winehq.org/wine-builds/ubuntu/ xenial main'
    - sudo apt update
    - sudo apt install wine-stable -f
    - tar -Jxf resources/femm42.tar.xz --directory ~/.wine/drive_c/


install:
    - pip install -U pip
    - pip install -U pytest
    - pip install coverage tox-travis
    - pip install pygmsh
script:
    - tox

after_success:
    - pip install codecov
    - codecov -e TOXENV,DJANGO

notifications:
email: false
