site_name: TEAM35 - Multi-objective Pareto optimization of a solenoid
use_directory_urls: true
theme:
  name: material
  language: en
  features:
    - navigation.sections
  plugins:
    - search
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      linenums_style: pymdownx-inline
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.critic
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      #emoji_index: !!python/name:materialx.emoji.twemoji
      #emoji_generator: !!python/name:materialx.emoji.to_svg
extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
nav:
  - Home:
    - index.md
    - 02-usage.md
    - 03-model.md
    - 04-references.md
  - Other:
    - previous-index.md
