site_name: power_transformer
use_directory_urls: true
theme:
  name: material

nav:
  - Home: index.md

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

  - footnotes


extra_javascript:
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js